name: vercel-env-push-action
description: Sync env vars with a vercel project
author: pentible
branding:
  icon: refresh-cw
  color: gray-dark

runs:
  using: node20
  main: dist/index.js

inputs:
  vercelToken:
    description: The Vercel token used to authenticate with the Vercel API.
    required: true
  projectId:
    description: The name/id of the Vercel project to push to (often repo name).
    required: true
  target:
    description:
      The name of the Vercel environment to push to (production, preview, or
      development)
    required: true
  gitBranch:
    description:
      The name/id of the git branch to push to (only when target is preview).
  envs:
    description:
      The new environment variables to push (JSON map of env var names to
      values).
    required: true

outputs:
  removed:
    description: List of the removed env vars
  changed:
    description: List of the changed env vars
  added:
    description: List of the added env vars
  unchanged:
    description: List of the unchanged env vars
  # TODO: output api results per env
