name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Action
        id: action
        uses: ./
        with:
          # TODO: add inputs
          check-name: Validate
      - name: Print Output
        run: echo "${{ steps.action.outputs.conclusion }}"
